= What's new?

[[what-s-new-in-3-2-since-3-1]]
== What's New in 3.2 Since 3.1
:page-section-summary-toc: 1

This section covers the changes made from version 3.1 to version 3.2.
For changes in earlier version, see xref:appendix/change-history.adoc[Change History].

[[x32-kafka-streams-iqs-support]]
=== Kafka Streams Interactive Query Support

A new API `KafkaStreamsInteractiveQuerySupport` for accessing queryable stores used in Kafka Streams interactive queries.
See xref:streams.adoc#kafka-streams-iq-support[Kafka Streams Interactive Support] for more details.



[[x32-tiss]]
=== TransactionIdSuffixStrategy

A new `TransactionIdSuffixStrategy` interface was introduced to manage `transactional.id` suffix.
The default implementation is `DefaultTransactionIdSuffixStrategy` when setting `maxCache` greater than zero can reuse `transactional.id` within a specific range, otherwise suffixes will be generated on the fly by incrementing a counter.
See xref:kafka/transactions.adoc#transaction-id-suffix-fixed[Fixed TransactionIdSuffix] for more information.

[[x32-async-return]]
=== Async @KafkaListener Return

`@KafkaListener` (and `@KafkaHandler`) methods can now return asynchronous return types include `CompletableFuture<?>`, `Mono<?>` and Kotlin `suspend` functions.
See xref:kafka/receiving-messages/async-returns.adoc[Async Returns] for more information.

[[x32-customizable-dlt-routing]]
=== Routing of messages to custom DLTs based on thrown exceptions

It's now possible to redirect messages to the custom DLTs based on the type of the exception, which has been thrown during the message processing.
Rules for the redirection are set either via the `RetryableTopic.exceptionBasedDltRouting` or the `RetryTopicConfigurationBuilder.dltRoutingRules`.
Custom DLTs are created automatically as well as other retry and dead-letter topics.
See xref:retrytopic/features.adoc#exc-based-custom-dlt-routing[Routing of messages to custom DLTs based on thrown exceptions] for more information.

[[x32-cp-ptm]]
=== Deprecating ContainerProperties transactionManager property

Deprecating the `transactionManager` property in `ContainerProperties` in favor of `KafkaAwareTransactionManager`,  a narrower type compared to the general `PlatformTransactionManager`. See xref:kafka/container-props.adoc#kafkaAwareTransactionManager[ContainerProperties] and xref:kafka/transactions.adoc#transaction-synchronization[Transaction Synchronization].

[[x32-after-rollback-processing]]
=== After Rollback Processing

A new `AfterRollbackProcessor` API `processBatch` is provided.
See xref:kafka/annotation-error-handling.adoc#after-rollback[After-rollback Processor] for more information.

[[x32-retry-topic]]
=== Change @RetryableTopic SameIntervalTopicReuseStrategy default value
Change `@RetryableTopic` property `SameIntervalTopicReuseStrategy` default value to `SINGLE_TOPIC`.
See xref:retrytopic/topic-naming.adoc#single-topic-maxinterval-delay[Single Topic for maxInterval Exponential Delay].

[[x32-seek-offset-compute-fn]]
=== New API method to seek to an offset based on a user provided function
`ConsumerCallback` provides a new API to seek to an offset based on a user-defined function, which takes the current offset in the consumer as an argument.
See xref:kafka/seek.adoc#seek[Seek API Docs] for more details.

[[x32-topic-partition-offset-constructor]]
=== New constructor in TopicPartitionOffset that accepts a function to compute the offset to seek to
`TopicPartitionOffset` has a new constructor that takes a user-provided function to compute the offset to seek to.
When this constructor is used, the framework calls the function with the input argument of the current consumer offset position.
See xref:kafka/seek.adoc#seek[Seek API Docs] for more details.

